"""Bill entity  -  a recurring or one-time expense."""

from dataclasses import dataclass

from clear_budget.domain.value_objects.amount import Amount
from clear_budget.domain.value_objects.year_month import YearMonth


@dataclass(frozen=True, slots=True)
class Bill:
    """A bill or expense entry (template for future months).

    Attributes:
        id: Unique identifier (auto-generated by repository)
        name: Human-readable name (e.g., "Rent", "Electricity")
        amount: Monthly amount due
        payment_method_id: Which account/card to debit (FK to PaymentMethod)
        category: Type of bill (housing, utilities, subscriptions, credit_payment, groceries, discretionary, one_time)
        bill_type: fixed | variable | expiring
        day_of_month: Day bill is due (1-31, None if not tied to a specific day)
        start_ym: First month this bill appears (YYYY-MM)
        end_ym: Last month this bill appears (None = perpetual)
        active: Whether this template is currently in use
    """

    id: int
    name: str
    amount: Amount
    payment_method_id: int
    category: str
    bill_type: str
    day_of_month: int | None
    start_ym: YearMonth
    end_ym: YearMonth | None
    active: bool = True
    target_card_id: int | None = None
    skipped_for_month: bool = False

    def is_active_in_month(self, year_month: YearMonth) -> bool:
        """Check if this bill is active in the given month."""
        if not self.active:
            return False
        if year_month < self.start_ym:
            return False
        if self.end_ym is not None and year_month > self.end_ym:
            return False
        return True

    def __str__(self) -> str:
        return f"{self.name} ({self.amount})"
