"""Commitment entity  -  money owed later that this month's table cannot see.

A commitment is an obligation the projection would otherwise be blind to: an
annual insurance premium, an MOT, Christmas. It is NOT a bill. A bill leaves
the account on a day inside the month being read; a commitment is money that
has to be held back over the months BEFORE the day it leaves, so the figure
the user is offered stops counting it as spendable.

The ending rule matches bills and income exactly: a commitment that stops
carries a final month rather than being deleted, so a month that really did
hold a reserve keeps it when it is read back out of the archive.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from clear_budget.domain.value_objects.amount import Amount
from clear_budget.domain.value_objects.recurrence import Recurrence
from clear_budget.domain.value_objects.year_month import YearMonth
from clear_budget.shared.errors import InvalidCommitmentError


@dataclass(frozen=True, slots=True)
class Commitment:
    """One obligation being reserved for.

    Attributes:
        id: Unique identifier (auto-generated by the repository)
        name: What the money is for (e.g. "Car insurance")
        amount: The full amount of ONE occurrence
        due_date: The day the next occurrence falls due
        recurrence: How often it comes round again
        created_month: The month the commitment was entered, which is where
            the first cycle starts accruing from
        already_held: What the user says is already put by for this occurrence
        category: Optional, reusing the existing bill categories
        active: Whether it is currently being reserved for
        final_month: The last month it applies to; None while it continues
    """

    id: int
    name: str
    amount: Amount
    due_date: date
    recurrence: Recurrence
    created_month: YearMonth
    already_held: Amount = Amount(pence=0)
    category: str | None = None
    active: bool = True
    final_month: YearMonth | None = None

    def __post_init__(self) -> None:
        """Reject a commitment that could not describe a real obligation."""
        if not self.name.strip():
            raise InvalidCommitmentError("Commitment needs a name")
        if self.final_month is not None and self.final_month < self.created_month:
            raise InvalidCommitmentError("Commitment cannot end before it starts")

    @property
    def outstanding_pence(self) -> int:
        """What still has to be found for this occurrence.

        Never negative: a user who says more is held than the bill costs has
        over-held rather than earned a credit, so the surplus is ignored here
        and the reserve is capped at the amount itself.
        """
        return max(self.amount.pence - self.already_held.pence, 0)

    def applies_to(self, month: YearMonth) -> bool:
        """Whether this commitment is being reserved for during `month`."""
        if not self.active:
            return False
        if month < self.created_month:
            return False
        return self.final_month is None or month <= self.final_month

    def applies_on(self, day: date) -> bool:
        """Whether this commitment is being reserved for on `day`."""
        return self.applies_to(YearMonth(year=day.year, month=day.month))
